services:
  nginx:
    image: nginx:alpine3.21
    container_name: nginx_proxy_daskomrec25
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ${PWD}/docker/nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx config
      - ${PWD}:/var/www/
    depends_on:
      - daskomrec25
      - cache-npm-daskomrec25
      - cache-composer-daskomrec25

  daskomrec25:
    build: 
      context: .
    volumes:
      - ${PWD}:/var/www/
    command: "php-fpm -F"
    user: "1000:1000"
    expose:
      - "9000"
    depends_on:
      - cache-npm-daskomrec25
      - cache-composer-daskomrec25

#########################################
#        NPM AND COMPOSER CACHE         #
#########################################

  cache-npm-daskomrec25:
    image: node:lts-alpine3.21
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "[ ! -d ./public/build ] && npm install && npm run build || echo 'Build already exists, skipping...'"
    user: "1000:1000"
    restart: "no"
    depends_on:
      - cache-composer-daskomrec25

  cache-composer-daskomrec25:
    image: php:8.3.17-fpm-alpine3.21
    working_dir: /var
    volumes:
      - .:/var
    command: >
      sh -c "
        if ! command -v composer >/dev/null 2>&1; then
          curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer;
        fi;
        if [ ! -d ./vendor ]; then
          composer install --optimize-autoloader --no-dev --ignore-platform-req=ext-gd --ignore-platform-req=ext-zip;
        else
          echo 'Vendor folder already exists, skipping...';
        fi
        chown -R 1000:1000 ./vendor"
    restart: "no"